(print (atom nil))
(print (atom t))
(print (atom 42))
(print (atom "string"))
(print (atom '(1 2 3)))
(print (listp nil))
(print (listp t))
(print (listp 42))
(print (listp "string"))
(print (listp '(1 2 3)))
(print (null nil))
(print (null t))
(print (null 42))
(print (null "string"))
(print (null '(1 2 3)))
(print (consp '(1.2)))
(print (consp '( 1 2 3)))
(print (consp '()))
(print (consp 42))
(print (zerop 0))
(print (zerop 42))
